### ISSUE TITLE
Schematics are hard to read

### ISSUE THREAD

**Issue by clydeshappee** [Hagtronics/Battery-Analyzer#1]
Hello, 

I am finding the schematics very difficult to read.   It looks like the pages are all on E sized sheets, but would fit nicely on B size and be easier to read, print and work with.  One sheet has a lot on it and I would suggest that it be split up into to.

I really want to build this, but I am at a loss for doing so with the sheet sizes.  My eyes are much older than yours.

Any assistance here will be appreciated.

Clyde

**Comment by Hagtronics** [comment]
Hello Clyde - With a computer you can print at any size you want. The schematic is a high resolution PDF, you can view it on screen and then "Print Current View".  With this method you can print an entire Resistor symbol to fit on a 8.5 x 11 sheet.

Hope this helps.

**Comment by clydeshappee** [comment]
That just means I have to chop it up into bite size pieces and the flow is
lost.

I would like to not work so hard on a simple print.

**Comment by Hagtronics** [comment]
Sorry you don't like what I have given for free. 
Slicing the schematic into pieces will also 'break the flow' as you now are taking issue with. As it stands the schematic sheets re compartmentalized and flow nicely, but everyone's opinion of that will of course vary.
I am afraid that you are never going to be happy with anything I do, and that I have given for free, so I am sorry for that.
